name: deploy-backend
on:
  push:
    branches: [main]
    paths: ['apps/backend/**']
  workflow_dispatch:
permissions:
  contents: read
jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
